### ISSUE TITLE
Encrypt passwords "right" or not at all

### ISSUE THREAD

**Issue by ccoenen** [dzaporozhets/passty#1]
The current implementation of the password encryption doesn't really do anything. The secret is directly derived from your email address and also stored in the database. At that level, you could just as well base64-encode them (so they're not easily visible in a SQL-Dump).

I'm specifically refering to 

https://github.com/dzaporozhets/passty/blob/3be376a6cbac1c8948aa711c4f75f2d62e03fe02/app/models/password.rb#L22-L24

which uses

https://github.com/dzaporozhets/passty/blob/daef2a611e608ea09034244fc1037a96520df943/app/models/user.rb#L39-L42

and

https://github.com/dzaporozhets/passty/blob/daef2a611e608ea09034244fc1037a96520df943/app/models/user.rb#L46-L48

The current solution does not offer any security in case of a server breach. It's also not hard to decrypt the whole database, you don't even have to guess or brute-force anything, it's all there.

In case there's no security breach, you still put a lot of trust into the guy running the server. (OK, technically that is still a security breach of sorts).

Currently, the passwords also don't support any kind of forward-compatibility. At least the passwords could store in which way they were encrypted (like "v1") so you could implement this more securely later-on (and not lose all the old-style-encrypted passwords in the process).

The passwords could be encrypted to something NOT in the database. You could, for example, derive a secret from the _password_ and store it in the session. The password itself is not in the databse and also not in RAM (except at the moment of login). On the downside, this makes API-Tokens and similar things next to impossible. But at least, you are less likely to lose all your passwords at once to an attacker.

**Comment by ccoenen** [comment]
One thing that you should definitely look into is client-side encryption. This could be added on top of the current model pretty easily. This way, the secret wouldn't even have to be transmitted to the server. So far, i didn't see anything like it in the code. The whole database would be useless for an attacker, which also lets you sleep a lot better.

**Comment by dzaporozhets** [comment]
@ccoenen thank you for feedback. 
I like your idea with client side encryption. But if attacker can browse source code of application he can decrypt db right?

**Comment by ccoenen** [comment]
Only if the attacker has the secret. That's why it shouldn't be stored persistently alongside with the encrypted data.

If the crypto itself is secure (i think, we can assume AES256 used in ActiveSupport is secure enough for our needs), and the secret is unknown, all the encrypted stuff will remain safe - even if the application's sourcecode is known. The only attack vector, then, is brute force or educated guesses or keyloggers.

Interesting examples of encryption are KeePass and TrueCrypt. Both of them derive a secret from your password (which itself isn't stored). Both keep that secret in RAM only. In the case of KeePass, the secret is "forgotten" after "locking" the workspace (which TrueCrypt can't really do, as you'd lose access to the mounted disk in an uncontrolled fashion).

Another system worth looking at, is Mozilla Sync. They also do all their encryption on the client, the server doesn't store anything decipherable. The server itself isn't that complicated. Similarly, megaupload encrypts files before storing them (their motivation is a different one: they want plausible deniability so they don't have to take down files).

@ mdjanic on twitter refered me to https://github.com/clipperz/javascript-crypto-library - which i previously didn't know and haven't thoroughly checked. But It might be a good starting point for client-side crypto.

**Comment by dzaporozhets** [comment]
But if we encrypt with secret stored in session - we wont be able to restore saved passwords after session expires.

**Comment by ccoenen** [comment]
If the secret is directly derived from the user's login-password, you could always do that derivation process on login, store the derived key in the session. It's very similar to the process you're doing with the email-adress right now. Putting in the same email will always yield the same secret. Likewise will the same password yield the same key. With the advantage that neither the password nor the derived key are stored with the encrypted data.

However, this comes with two drawbacks: you'd have to log in with a password every time you login (so no "remember me" checkbox), and as long as you're logged in, the session store also has the neccessary decryption details in it. So sessions should expire fairly quickly (a little like the auto-lock timeout in KeePass).

I'm also not so sure how/if rails "garbage-collects" session information cleanly. That one might depend on the session-storage in use.

Client-side encryption is a little easier in that regard, in that case at least you need to compromise two distinct systems at once (user's browser and the server).

**Comment by dzaporozhets** [comment]
makes sense for me. I'm going to try implementing this soon

**Comment by dzaporozhets** [comment]
2 things I'm still not sure about client side.
1. If I use email + know app source code I can check what fields used for generating encryption key. SInce I have db I can easily generate it by my own.
2. If I use email+password for generating encryption key then I was not able to change my password since then I loose access to stored passwords.

**Comment by ccoenen** [comment]
Regarding the second item: In many apps, it's customary to provide the "old" password in the process of changing the password. In that case, you could go over all the entries, decrypt from the old password and then re-encrypt to the new password.

(password, in this process, could also be a password-derived secret)

**Comment by ccoenen** [comment]
But "Password-recovery"-Style Password change would be impossible, that's right.

**Comment by stayallive** [comment]
What is the current status on this? Still wanting to implement this?

If i'm reading this right the current situation means that the person that hosts the Passty instance can decrypt all password because he holds the private key. The change would mean even the instance owner cannot decrypt it but only the user that inserted the password right (like mega.co.nz does)?

So this is only an issue when (for instance) I am giving other people access and they want to be sure there passwords are safe, even from me?

Thanks in advance!

**Comment by ccoenen** [comment]
Anyone who gets their hands on the database has all the neccessary information.

This would include the sysadmin (best case), sysadmin + various intelligence agencies (likely case) or anyone (if the server is attackable). This sounds harsh, but with the recent hacks of companies like Sony, Ebay and Adobe and bugs in other libraries like Hearbleed, there really is no way to say "that would _never_ happen on my server".

If you are the admin AND only user of passty. AND you're hosting it only on a local, trusted network AND have your server properly configured, then there is nothing to worry about. Given that the Readme refers to Heroku Hosting, this is probably not the use case the author has in mind.

Loosely related, but not yet discussed: Using this project over a non-encrypted connection would obviously be a very bad idea. Every stop between you and your rails-server could read your passwords in plain text. That includes people on the same WiFi.

**Comment by stayallive** [comment]
Thanks for your detailed explanation!

Would love to hear from @randx if you are still interested in "fixing" this when you find the time?

**Comment by dzaporozhets** [comment]
ok so possible implementation will look like this: 
- encrypt with use password on server side (still problem with non-encrypted connection)
- encrypt on client side using js (sounds secure but I need to validate user password on client side somehow or typo can cause encryption with wrong password)

**Comment by dzaporozhets** [comment]
so possible solution looks like this: 
- ask user for master password (key) and encrypt on client side using JS
- send encrypted password to server (rails app)
- get encrypted password from server and encrypt on client side using master password

In this case no sense to store master password on server side. So we have one password for login which is stored encrypted on server but not related to app passwords. In this case we have next picture: 
- you encrypt your password with some key which is not validated anywhere because it is not stored nowhere because we want secure solution. 
- in this case you can use different keys for encrypting different passwords
- if you made a key typo during encryption/decryption its impossible to notify you about this
- if someone hacked your account he wont be able to get app password anyway (which is good)

I think it affects usability in bad way but allow to use app at heroku or other storages without fear being hacked. All you need is to be careful and possibly use always one key for encrypting all password

**Comment by ccoenen** [comment]
I think, using this project over an unencrypted connection is a bad idea in any case, so from _my_ point of view, i would not encourage it. People can simply use self-signed Certificates, or CA-Cert, or StartSSL, which are all ways to get to TLS for free (or very cheap).

Among the reasons: If you are on an insecure line, anybody could just eavesdrop on your connection, and seamlessly replace javascript. If i were an attacker, i'd sit in on your connection, wait for crypto-library.js and replace its content with my slightly better version (better in that it also sends decrypted data to my server).

So, even with the second scenario (fully encrypted on the client side), connection security is extremely important. This can, of course, also be achieved with VPN, but i think a strong warning on unencrypted HTTP is warranted.

**Comment by ccoenen** [comment]
regarding the "how will i know, if the password/key was correct?": In TLS, i think, this is done with "HMAC then Encrypt". Basically, you do this, imagine the encrypted password is "secret":
- sha256("secret") => abcdef1234....
- aes("secret" + "abcdef1234....") => [crypto-madness ensues]

Whenever you're now decrypting anything, you can check, if the last 64 characters are EXACTLY the sha256 of the other characters. Then you know that it's decrypted correctly.

**Comment by dzaporozhets** [comment]
I like the idea about how to validate decryption :smile:

**Comment by dzaporozhets** [comment]
I created merge request for client side encryption using js library https://gitlab.com/dzaporozhets/passty/merge_requests/1

**Comment by ccoenen** [comment]
regarding this line [prompting for an encryption key](https://gitlab.com/dzaporozhets/passty/blob/6ba8eb8f080bc4d1358a58d337d62991faa5edb5/app/assets/javascripts/passwords.js.coffee#L20), i'd like to ask how it will work from a user's perspective.

From what i read (and i may well be wrong!), it looks like i can specify a different encryption key for every single password. If i mistype my encrption key, i'll be unable to access that password later, right?

**Comment by dzaporozhets** [comment]
>  it looks like i can specify a different encryption key for every single password. If i mistype my encrption key, i'll be unable to access that password later, right?

right. Since we dont store it anywhere we cant validate it

**Comment by dzaporozhets** [comment]
Closing this one since password is encrypted/decrypted now on client side.
